name: Metrics
on:
  schedule: [{cron: "0 */12 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: YUSEF-RAMY
          template: classic
          config_timezone: Africa/Cairo
          
          # ضفنا هنا repositories عشان يقدر يقرأ الـ Stars بتاعتك
          base: header, activity, community, repositories
          
          # بنحدد إيه اللي يظهر في الأنشطة (الـ Commits والـ Pull Requests بس)
          base_activity: commits, pullrequests
          
          # بنحدد إيه اللي يظهر في الكوميونيتي (المتابعين بس)
          base_community: followers
          
          # بنحدد إيه اللي يظهر من المستودعات (الـ Stars والـ Repositories اللي أنت تملكها بس)
          base_repositories: starred, featured
          
          # تجاهل لغات الجوبيتر والـ CSS والـ HTML عشان يفضل البروفايل رايق ومقتصر على لغاتك الأساسية
          ignored_languages: jupyter notebook, html, css
