name: Metrics
on:
  schedule: [{cron: "0 */12 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: YUSEF-RAMY
          template: classic
          config_timezone: Africa/Cairo
          
          # بنعرض الهيدر الأساسي والـ ليدر بورد الأخضر فقط
          base: header
          
          # تفعيل ميزة إظهار عدد الـ Stars (النجوم) بشكل رايق
          plugin_stars: yes
          plugin_stars_limit: 4

          # تفعيل إضافة الأسطر المكتوبة (الـ Commits الذكية)
          plugin_lines: yes

          # تفعيل فلتر اللغات عشان نخفي جوبيتر و HTML و CSS تماماً
          plugin_languages: yes
          plugin_languages_ignored: jupyter notebook, html, css
